"""Wire layout of the noise session resume messages, kept import free."""

from __future__ import annotations

RESUME_OFFER_VERSION = 0x01
RESUME_ACCEPT_VERSION = 0x01
RESUME_SESSION_ID_SIZE = 8
RESUME_NONCE_SIZE = 16
RESUME_MAC_SIZE = 16
RESUME_SECRET_SIZE = 32

# version | session_id | client_nonce | offer_mac
RESUME_OFFER_SIZE = 1 + RESUME_SESSION_ID_SIZE + RESUME_NONCE_SIZE + RESUME_MAC_SIZE
RESUME_OFFER_SESSION_ID_OFFSET = 1
RESUME_OFFER_NONCE_OFFSET = RESUME_OFFER_SESSION_ID_OFFSET + RESUME_SESSION_ID_SIZE
RESUME_OFFER_MAC_OFFSET = RESUME_OFFER_NONCE_OFFSET + RESUME_NONCE_SIZE
# version | server_nonce | confirm_mac
RESUME_ACCEPT_SIZE = 1 + RESUME_NONCE_SIZE + RESUME_MAC_SIZE
