# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_options.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi_options.proto\x1a google/protobuf/descriptor.proto\"\x06\n\x04void*F\n\rAPISourceType\x12\x0f\n\x0bSOURCE_BOTH\x10\x00\x12\x11\n\rSOURCE_SERVER\x10\x01\x12\x11\n\rSOURCE_CLIENT\x10\x02:E\n\x16needs_setup_connection\x12\x1e.google.protobuf.MethodOptions\x18\x8e\x08 \x01(\x08:\x04true:C\n\x14needs_authentication\x12\x1e.google.protobuf.MethodOptions\x18\x8f\x08 \x01(\x08:\x04true:/\n\x02id\x12\x1f.google.protobuf.MessageOptions\x18\x8c\x08 \x01(\r:\x01\x30:M\n\x06source\x12\x1f.google.protobuf.MessageOptions\x18\x8d\x08 \x01(\x0e\x32\x0e.APISourceType:\x0bSOURCE_BOTH:/\n\x05ifdef\x12\x1f.google.protobuf.MessageOptions\x18\x8e\x08 \x01(\t:3\n\x03log\x12\x1f.google.protobuf.MessageOptions\x18\x8f\x08 \x01(\x08:\x04true:9\n\x08no_delay\x12\x1f.google.protobuf.MessageOptions\x18\x90\x08 \x01(\x08:\x05\x66\x61lse')

_APISOURCETYPE = DESCRIPTOR.enum_types_by_name['APISourceType']
APISourceType = enum_type_wrapper.EnumTypeWrapper(_APISOURCETYPE)
SOURCE_BOTH = 0
SOURCE_SERVER = 1
SOURCE_CLIENT = 2

NEEDS_SETUP_CONNECTION_FIELD_NUMBER = 1038
needs_setup_connection = DESCRIPTOR.extensions_by_name['needs_setup_connection']
NEEDS_AUTHENTICATION_FIELD_NUMBER = 1039
needs_authentication = DESCRIPTOR.extensions_by_name['needs_authentication']
ID_FIELD_NUMBER = 1036
id = DESCRIPTOR.extensions_by_name['id']
SOURCE_FIELD_NUMBER = 1037
source = DESCRIPTOR.extensions_by_name['source']
IFDEF_FIELD_NUMBER = 1038
ifdef = DESCRIPTOR.extensions_by_name['ifdef']
LOG_FIELD_NUMBER = 1039
log = DESCRIPTOR.extensions_by_name['log']
NO_DELAY_FIELD_NUMBER = 1040
no_delay = DESCRIPTOR.extensions_by_name['no_delay']

_VOID = DESCRIPTOR.message_types_by_name['void']
void = _reflection.GeneratedProtocolMessageType('void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'api_options_pb2'
  # @@protoc_insertion_point(class_scope:void)
  })
_sym_db.RegisterMessage(void)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(needs_setup_connection)
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(needs_authentication)
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(id)
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(source)
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(ifdef)
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(log)
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(no_delay)

  DESCRIPTOR._options = None
  _APISOURCETYPE._serialized_start=63
  _APISOURCETYPE._serialized_end=133
  _VOID._serialized_start=55
  _VOID._serialized_end=61
# @@protoc_insertion_point(module_scope)
