#!/bin/bash

cd "$(dirname "$0")/.."
set -euxo pipefail

black --safe aioesphomeapi tests
pylint aioesphomeapi
ruff check aioesphomeapi tests
ruff format --check aioesphomeapi tests
isort aioesphomeapi tests
mypy aioesphomeapi
pytest tests
