name: Check protobuf generated files

on:
  pull_request:
    paths:
      - aioesphomeapi/api_options_pb2.py
      - aioesphomeapi/api_pb2.py
      - aioesphomeapi/api.proto
      - aioesphomeapi/api_options.proto
      - Dockerfile

jobs:
  protoc-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate protoc
        run: |
          docker run \
            -v "$PWD":/aioesphomeapi \
            ghcr.io/esphome/aioesphomeapi-proto-builder:latest

      - name: Check changes
        run: |
          if ! git diff --quiet; then
            echo "You have altered the generated proto files but they do not match what is expected."
            echo "Please run the following to update the generated files:"
            echo 'docker run -v "$PWD":/aioesphomeapi ghcr.io/esphome/aioesphomeapi-proto-builder:latest'
            exit 1
          fi
